[package]
name = "ringbuf"
version = "0.1.0"
edition = "2024"

[dependencies]
libc.workspace = true
loom = { version = "0.7.2", optional = true }

# В Cargo.toml crate'а, где будут loom-тесты (например crates/ringbuf/Cargo.toml)
[dev-dependencies]
loom = "0.7"

[loom]
# Loom использует feature flag
[features]
loom = ["dep:loom"]