pub const LS_FILE_PAGE_SIZE: usize = 4096;
pub const SNAPSHOT_RECORD_MAGIC: u64 = 0x5250_4E53_5453_444C;

pub const STORAGE_FILE_TYPE_POSTING: u8 = 1;
pub const STORAGE_FILE_TYPE_SNAPSHOT: u8 = 2;
pub const STORAGE_FILE_TYPE_SIGNATURE: u8 = 3;
pub const STORAGE_FILE_TYPE_METADATA: u8 = 4;
